name: automation testing pipeline

on:
  push:
    branches:
      -main

jobs:
  automation-tests:
    runs-on: windows-latest

  steps:
  -name: checkout repository
  -uses: actions/checkout@v3

  -name: Set up Java (JDK 11)
  -uses: actions/setup-java@v3
   with:  
    distribution: 'temurin'
    java-version: '11'

  -name: setup Chrome driver version
   run:
     choco install googlechrome
     choco install chromedriver
     Chromedriver --version

  -name: permission to gradle for execution
   run:  chmod +x gradlew

  -name: build project with gradle
   run: .\gradlew.bat build

  -name: Run Automation tests
  run: ./gradlew.bat tests

  -name: upload tests report
    if: always()
    uses: actions/upload-artifacts@v3
    with:
      name: test-reports
      path: build/report/reports/test
